### ISSUE TITLE
Дубликаты заданий в пулах NOUN&anim@NOUN&inan

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#793]
У 171 задания есть дубликаты. Кажется, удалять уже поздно. Но я не помню, откуда они взялись.

**Comment by Shimorina** [comment]
возможно, см. https://github.com/OpenCorpora/opencorpora/issues/756#issuecomment-233562832

**Comment by grandsbor** [comment]
171 - это id типа пулов?


6 янв 2017 г. 23:01 пользователь "Anastasia Shimorina" <
notifications@github.com> написал:

возможно, см. #756 (comment)
<https://github.com/OpenCorpora/opencorpora/issues/756#issuecomment-233562832>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenCorpora/opencorpora/issues/793#issuecomment-270992020>,
or mute the thread

**Comment by grandsbor** [comment]
Больше не должно повторяться, пишите, если что
